# Generated by Django 4.1.6 on 2023-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('content', models.CharField(help_text='Write your quote here', max_length=150)),
                ('author', models.CharField(help_text='The author of the quote', max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
